### ISSUE TITLE
NG+ map capure not working properly

### ISSUE THREAD

**Issue by RNG42** [Dadido3/noita-mapcap#8] opened 2021-01-04 15:48 UTC
It seems that only already visited chunks are captured properly, otherwise the chunks seem to be the ones from the main world resulting in a partly corrupt map output. I wanted to capture the aftermath of my current NG++ map.  

Tested on the latest version of Noita (Dev Build Dec 1 2020). No other mods beside mapcap were active.

**Comment by Dadido3** [comment] 2021-01-04 17:48
Did you transfer your save game from the normal `noita.exe` to the `noita_dev.exe`?

Assuming you did copy it over, i can think of two ways this can cause problems:
- Either there is something missing when you copied the save game, and Noita is regenerating the normal world because it doesn't know it is in NG(++).
- Or you have copied your save into the already exísting save00 folder, and there is still old chunk data left.

You probably just have to remove the `save00` directory before you copy your save game over.

If you didn't copy the save game over i need more info about the problem.

**Comment by RNG42** [comment] 2021-01-04 18:38
I copied all save files from "AppData\LocalLow\Nolla_Games_Noita\save00" to "Steam\steamapps\common\Noita\save00", but indeed WITHOUT deleting the files previously existing. I'll try it again and delete all old save files before copying. will reply if it worked.

**Comment by RNG42** [comment] 2021-01-04 19:08
So, i deleted all files before copying the save folder, but the issue still persists. 

I started a new NG+ and went down a few chunks to generate the actual NG+ map while leaving everything else untouched. You can see that the mines have a different biome this time, the lava lake should not have been generated at all in NG+. Now when i actually play further to reach this area, Fungal Caverns were generated instead of the Lava lake.

![Output](https://user-images.githubusercontent.com/21169392/103569591-de4d5300-4ec7-11eb-93c0-605804691661.png)

**Comment by Dadido3** [comment] 2021-01-04 20:42
I just tested it myself, and i completely wiped all settings and data that `noita_dev.exe` uses. I get exactly the same result:

![shot_20210104-211248-1200860829-3440-925-00127230](https://user-images.githubusercontent.com/6549004/103575419-02159680-4ed2-11eb-9926-64124b4e340a.png)

I also copied the stats folder over to be sure (`...\AppData\LocalLow\Nolla_Games_Noita\save00\stats` to `...\SteamApps\common\Noita\save_stats`), but that didn't help.

The savegames really seem to be incompatible between the two versions. No idea what you could do to fix it, maybe someone in the Noita discord has any idea.

Also, you could try to do the capture with the normal `noita.exe`, but you'll have to adjust the resolution. Also there will be fog of war:

![grafik](https://user-images.githubusercontent.com/6549004/103577506-3e96c180-4ed5-11eb-9e41-1d910b545c0c.png)

**Comment by RNG42** [comment] 2021-01-04 21:05
I also did a fresh reinstall of Noita because of leftovers from the unpacked modding files (wang_gen.exe). The Beta branch has the same issue beyond that.

One thing i noticed is that in "\Noita\save00" the files "magic_numbers.xml" and "session_numbers.xml" got generated after loading the save from noita_dev.exe. These are not present in the regular save folder.

**Comment by Dadido3** [comment] 2021-01-04 21:10
Oh, that could be the cause of the issue. The normal `noita.exe` encrypts these two files (with the file suffix `.salakieli`). If you could encrypt it, and put the content into the corresponding `.xml` file it could work.

**Comment by Dadido3** [comment] 2021-01-04 21:17
Here is a project that can manage your save files, it also seems to be able to encrypt/decrypt the salakieli files: [github.com/R4wizard/NoitaSaveManager](https://github.com/R4wizard/NoitaSaveManager/releases)

**Comment by Dadido3** [comment] 2021-01-04 21:39
Ok, that program seems to have stopped working with the current Noita. But i took the key from the source and put it into [CyberChef](https://gchq.github.io/CyberChef/#recipe=AES_Decrypt(%7B'option':'UTF8','string':'KnowledgeIsTheHi'%7D,%7B'option':'UTF8','string':'WhoWouldntGiveEv'%7D,'CTR','Raw','Raw',%7B'option':'Hex','string':''%7D))

Just follow that link and drag and drop your `session_numbers.salakieli` into the input field. After that copy the content into your `session_numbers.xml`

**Comment by RNG42** [comment] 2021-01-04 21:55
It's actually working now! I assume the missing setting was ` NEW_GAME_PLUS_COUNT="3"` from "session_numbers.xml". So you might just change this value in the already generated xml to the actual NG+ count and it should work without decrypting the old salakieli file. This info should be noted somewhere. Thanks a lot for your help!

**Comment by RNG42** [comment] 2021-01-05 13:33
Basically everything works now, except for a few small things. The Lava lake is still generated as well as two holy mountains and other things which should not be there. Since this is not an issue of your mod, this thread can be closed. There might be other settings i'm missing, which cause the generation of these areas.
Thanks a lot for your help!

**Comment by Dadido3** [comment] 2021-01-05 14:07
I'll close this issue, but feel free to comment when you find a solution. I assume there are more people facing the same problem, so i could add this information to a troubleshooting section in the readme.

**Closed by Dadido3** 2021-01-05 14:07 UTC
